 
#ifndef APP_CONFIG_H_
#define APP_CONFIG_H_

#define LED_SIGNAL_IF_OPEN LOW
#define LED_SIGNAL_IF_CLOSE HIGH
#define PIN_RESET D1
#define SERIAL_BAUD_RATE 115200
#define JSON_BUFFER_LENGTH 1460

#endif /* APP_CONFIG_H_ */